--Nhân viên th? nh?t c?p nh?p giá ti?n cho s?n ph?m v?i product_id là 25.

--B1
SELECT PRODUCT_INFO_ID, CODE, NAME, PRICE
FROM PRODUCT_INFO
WHERE ACTIVE_FLAG = 1
AND PRODUCT_INFO_ID IN (25, 26);

--B2
UPDATE PRODUCT_INFO
SET PRICE = 145000
WHERE PRODUCT_INFO_ID = 25;

--B6
INSERT INTO PRODUCT_INFO(CATEGORY_ID, CODE, NAME) 
VALUES (62, 'FGH11A', 'Xi mang Hoa Tho');

--B9
COMMIT;

--B13
SELECT PRODUCT_INFO_ID, CODE, NAME, PRICE
FROM PRODUCT_INFO
WHERE ACTIVE_FLAG = 1
AND PRODUCT_INFO_ID IN (25, 26, 41);

