--Nhân viên th? nh?t c?p nh?p giá ti?n cho s?n ph?m v?i product_id là 25.

--B3
SET TRANSACTION
ISOLATION LEVEL
READ COMMITTED;

--B4
SELECT PRODUCT_INFO_ID, CODE, NAME, PRICE
FROM PRODUCT_INFO
WHERE ACTIVE_FLAG = 1
AND PRODUCT_INFO_ID IN (25, 26, 41);


--B5
UPDATE PRODUCT_INFO
SET PRICE = 170000
WHERE PRODUCT_INFO_ID = 26;

--B7
SELECT PRODUCT_INFO_ID, CODE, NAME, PRICE
FROM PRODUCT_INFO
WHERE ACTIVE_FLAG = 1
AND PRODUCT_INFO_ID IN (25, 26, 41);

--B8
UPDATE PRODUCT_INFO
SET PRICE = 175000
WHERE PRODUCT_INFO_ID = 25;

--B10
--CHECK QUERY RESULT

--B11
SELECT PRODUCT_INFO_ID, CODE, NAME, PRICE
FROM PRODUCT_INFO
WHERE ACTIVE_FLAG = 1
AND PRODUCT_INFO_ID IN (25, 26, 41);

--B12
COMMIT;

