SET SERVEROUTPUT ON;
--MODIFY DATE: 22/06/2020
--MODIFIED BY: NGUYEN NGOC CONG
--DESCRIPTION: CREATE TRIGGER TO UPDATE PRICE WHEN INSERT INVOICE DETAIL
CREATE OR REPLACE TRIGGER update_price_on_invoice
AFTER INSERT OR UPDATE OR DELETE ON INVOICE_DETAIL
FOR EACH ROW
DECLARE
  price_product PRODUCT_INFO.PRICE%TYPE;
BEGIN
  --GET CURRENT PRICE FROM PRODUCT 
  IF(INSERTING) THEN
    SELECT PRICE INTO price_product
    FROM PRODUCT_INFO PI
    WHERE PI.PRODUCT_INFO_ID = :NEW.PRODUCT_ID;
    UPDATE INVOICE 
    SET INVOICE.PRICE = PRICE + price_product*:NEW.QUANITY
    WHERE INVOICE_ID = :NEW.INVOICE_ID;
  END IF;
  IF(UPDATING) THEN
    SELECT PRICE INTO price_product
    FROM PRODUCT_INFO PI
    WHERE PI.PRODUCT_INFO_ID = :NEW.PRODUCT_ID;
  
    UPDATE INVOICE 
    SET INVOICE.PRICE = PRICE + price_product*:NEW.QUANITY
    WHERE INVOICE_ID = :NEW.INVOICE_ID;
    
    UPDATE INVOICE 
    SET INVOICE.PRICE = PRICE - price_product*:OLD.QUANITY
    WHERE INVOICE_ID = :OLD.INVOICE_ID;
  END IF;
  IF(DELETING) THEN
    SELECT PRICE INTO price_product
    FROM PRODUCT_INFO PI
    WHERE PI.PRODUCT_INFO_ID = :OLD.PRODUCT_ID;
    UPDATE INVOICE 
    SET INVOICE.PRICE = PRICE - price_product*:OLD.QUANITY
    WHERE INVOICE_ID = :OLD.INVOICE_ID;
  END IF;
  
END;
--INSERT INTO INVOICE
INSERT INTO INVOICE(INVOICE_ID,"QLKHO_ADMIN"."INVOICE"."TYPE", USER_ID, PRICE) VALUES(1,2, 1, 0);
--INSERT INTO INVOICE_DETAIL
INSERT INTO INVOICE_DETAIL(INVOICE_ID, PRODUCT_ID, QUANITY) VALUES(1, 1, 3);
INSERT INTO INVOICE_DETAIL(INVOICE_ID, PRODUCT_ID, QUANITY) VALUES(1, 2, 1);
INSERT INTO INVOICE_DETAIL(INVOICE_ID, PRODUCT_ID, QUANITY) VALUES(1, 2, 1);
INSERT INTO INVOICE_DETAIL(INVOICE_ID, PRODUCT_ID, QUANITY) VALUES(1, 2, 1);
INSERT INTO INVOICE_DETAIL(INVOICE_ID, PRODUCT_ID, QUANITY) VALUES(1, 2, 1);

SELECT * FROM INVOICE;
SELECT * FROM INVOICE_DETAIL;
SELECT * FROM PRODUCT;

DELETE INVOICE_DETAIL
WHERE IN_DE_ID = 3;

--MODIFY DATE: 22/06/2020
--MODIFIED BY: NGUYEN NGOC CONG
--DESCRIPTION: CREATE TRIGGER TO CHECK QUANITY WHEN INSERT INVOICE DETAIL(EXPORT: INVOICE.TYPE = 2)
CREATE OR REPLACE TRIGGER CHECK_QUANITY_FOR_EXPORT
BEFORE INSERT ON INVOICE_DETAIL
FOR EACH ROW
BEGIN
  
END;
